/*
 * TIM2 milisecond timer driver - bare-metal, no HAL peripheral functions
 * library dependency
 *
 * Supports:
 *  - Blocking delay (TIM_Delay)
 *  - Configurable one-shot/periodic timer, polling or interrupt driven
 *
 * Assumes:
 *  - TIM2's timer input is 84MHz
 *  - Before calling TIM_Delay / TIM_Init, TIM_ClockEnable was called
 *
 * For interrupt driven mode caller must implement TIM_UserHandler function
 */

#ifndef TIM_Driver
#define TIM_Driver

#include <stdint.h>

#define CLOCK_HZ 84000000

/* one_shot / interrupt_driven are used as booleans (0 or 1) despite
 * unsigned int, larger value would not take any effect */
typedef struct {
    uint32_t millies;
    unsigned int one_shot;
    unsigned int interrupt_driven;
} TIM_Config_t;

typedef enum {
    TIM_ExitCode_Ok = 0,
    TIM_ExitCode_ZeroMsDelay = 1,
} TIM_ExitCode_t;

/* Enable TIM2 peripheral clock. Must be called before TIM_Init TIM_Delay */
void TIM_ClockEnable();

/* Lets configure one-shot/repeating timer polling or interrupt driven */
TIM_ExitCode_t TIM_Init(TIM_Config_t conf);

/* Blocking delay for 'millies' miliseconds. Reconfigures and takes
 * ownership of TIM2 for duration of the call */
TIM_ExitCode_t TIM_Delay(uint32_t millies);

TIM_ExitCode_t TIM_Start();
TIM_ExitCode_t TIM_Stop();

/* This should be implemented by user. Does not require user to
 * clear interrupt flag which was generated by update event */
void TIM_UserHandler();

#endif
